spring:
  application:
    name: simple-provider

zookeeper:
  address:  zookeeper.co:2181
  root-path:  '/simple'
  timeout:  9000
  data-path:  '/data'

simple:
  provider:
      port: 8080
server:
  port: 8080